graph TD
A[/]
A ---B1[bin]
A ---B2[boot]
A ---B3[dev]
A ---B4[etc]
A ---B5[lib]
A ---B6[tmp]
A ---B7[unix]
A ---B8[usr]
B8---C1[you]
B8---C2[mike]
B8---C3[paul]
B8---C4[mary]
C1---D1[junk]
C3---D2[junk]
C3---D3[temp]
C4---D4[junk]
C4---D5[temp]
